categories: [Proteomics]
description: Generate FASTA from FASTG
homepage_url: https://github.com/galaxyproteomics/fastg2protlib.git
long_description: Generate FASTA from FASTG
name: fastg2protlib-peptides
owner: galaxyp
remote_repository_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/fastg2protlib-peptides'
