categories: [Proteomics]
description: Validate FASTA from MSMS
homepage_url: https://github.com/galaxyproteomics/fastg2protlib.git
long_description: Generate FASTA from FASTG, validate FASTA based on MSMS
name: fastg2protlib-validate
owner: galaxyp
remote_repository_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/fastg2protlib-validate'
