categories:
- Proteomics
description: Generate protein FASTA from FASTG
long_description: |
    Generate protein FASTA from FASTG, validate protein FASTA based on MSMS
name: suite_fastg2protlib
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/suites/suite_fastg2protlib
type: repository_suite_definition
    